title: Flight Reports
description: This documents describe flight reports for hot air balloon competitions.
theme: just-the-docs

url: https://hakunom.github.io/balloon

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
